# Generated by Django 5.1.4 on 2025-01-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='customer_files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='attachments',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Site Visit', 'Site Visit'), ('Quote Sent', 'Quote Sent'), ('Payment Done', 'Payment Done')], max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='app.file'),
        ),
    ]
