# Generated by Django 5.1.4 on 2025-01-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file_remove_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='assigned_tasker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tasker'),
        ),
    ]
