# Generated by Django 5.1.4 on 2025-01-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_assigned_tasker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasker',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='app.customer'),
        ),
    ]
