# Generated by Django 5.1.4 on 2025-01-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='attachments',
        ),
        migrations.AddField(
            model_name='customer',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
