# Generated by Django 5.1.4 on 2025-01-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customer_attachments_customer_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='attachments',
        ),
        migrations.AddField(
            model_name='customer',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='app.file'),
        ),
    ]
