# Generated by Django 5.1.4 on 2025-01-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_customer_attachments_customer_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularcustomer',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='regularcustomer',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='other_documents/'),
        ),
        migrations.AddField(
            model_name='regularcustomer',
            name='service_dates',
            field=models.DateField(blank=True, null=True),
        ),
    ]
