# Generated by Django 5.1.4 on 2025-01-16 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_regularcustomer_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Site Visit', 'Site Visit'), ('Quote Sent', 'Quote Sent'), ('Payment Done', 'Payment Done'), ('Lead', 'Lead')], max_length=50),
        ),
    ]
