# Generated by Django 5.1.4 on 2025-01-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_leadjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadjob',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='leadjob',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='leadjob',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadjob',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
