# Generated by Django 5.1.4 on 2025-01-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_leadjob_address_leadjob_email_leadjob_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
