# Generated by Django 5.1.4 on 2025-01-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customer_company_name_customer_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularcustomer',
            name='contract_details',
            field=models.CharField(choices=[('Once a week', 'Once a week'), ('Twice a week', 'Twice a week'), ('Once a month', 'Once a month'), ('Twice a month', 'Twice a month'), ('3 times a month', '3 times a month'), ('Once every two months', 'Once every two months'), ('Twice every 2 months', 'Twice every 2 months')], default='Once a month', max_length=50),
        ),
    ]
