# Generated by Django 5.1.4 on 2025-01-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_regularcustomer_contract_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularcustomer',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='regularcustomer',
            name='other_documents',
        ),
        migrations.AddField(
            model_name='regularcustomer',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regularcustomer',
            name='contract_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='regularcustomer',
            name='service_dates',
            field=models.TextField(),
        ),
    ]
