# Generated by Django 5.1.4 on 2025-01-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_regularcustomer_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularcustomer',
            name='service_dates',
            field=models.DateField(blank=True, null=True),
        ),
    ]
