# Generated by Django 5.1.4 on 2025-01-18 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_regularcustomer_service_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularcustomer',
            name='service_dates',
        ),
    ]
