# Generated by Django 5.1.4 on 2025-01-18 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_regularcustomer_service_dates'),
    ]

    operations = [
    ]
