# Generated by Django 5.1.4 on 2025-01-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_customer_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularcustomer',
            name='service_dates',
            field=models.DateField(blank=True, null=True),
        ),
    ]
