# Generated by Django 5.1.4 on 2025-02-16 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_tasker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasker',
            name='user',
        ),
        migrations.AddField(
            model_name='completedjob',
            name='assigned_tasker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tasker'),
        ),
    ]
