# Generated by Django 5.1.4 on 2025-02-16 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_tasker_user_completedjob_assigned_tasker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasker',
            name='tasks',
        ),
    ]
