# Generated by Django 5.1.4 on 2025-02-17 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_tasker_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='category',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.AddField(
            model_name='partner',
            name='industry',
            field=models.CharField(default='exit', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='app.partner')),
            ],
        ),
    ]
