# Generated by Django 5.1.4 on 2025-02-17 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_name_company_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='name',
        ),
    ]
