# Generated by Django 5.1.4 on 2025-02-21 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_company_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.ForeignKey(default='Bellona', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='app.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.ForeignKey(default='Mobilya', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='app.partner'),
            preserve_default=False,
        ),
    ]
